"""add character relationships

Revision ID: bc594df4182d
Revises: e80d1d1f3685
Create Date: 2026-06-28 20:38:28.921897
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc594df4182d'
down_revision: str | None = 'e80d1d1f3685'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_relationships',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('character_a_id', sa.String(length=36), nullable=False),
    sa.Column('character_b_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timeline_info', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relationships_character_a_id'), 'character_relationships', ['character_a_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_character_b_id'), 'character_relationships', ['character_b_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_project_id'), 'character_relationships', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_relationships_project_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_b_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_character_a_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    # ### end Alembic commands ###
