"""add_workflow_review_memory_tables

Revision ID: cd42fd8f8e0e
Revises: 20260613_0001
Create Date: 2026-06-19 02:24:24.599290
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd42fd8f8e0e"
down_revision: str | None = "20260613_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timeline_events",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("scene_version_id", sa.String(length=36), nullable=True),
        sa.Column("event_text", sa.Text(), nullable=False),
        sa.Column("timeline_order", sa.Integer(), nullable=False),
        sa.Column("affected_character_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["novel_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_timeline_events_project_id"), "timeline_events", ["project_id"], unique=False)
    op.create_table(
        "workflow_runs",
        sa.Column("scene_id", sa.String(length=36), nullable=False),
        sa.Column("run_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("plan", sa.Text(), nullable=False),
        sa.Column("draft", sa.Text(), nullable=False),
        sa.Column("final_content", sa.Text(), nullable=False),
        sa.Column("prompt_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("context_manifest_json", sa.JSON(), nullable=False),
        sa.Column("events_json", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("version_created_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workflow_runs_scene_id"), "workflow_runs", ["scene_id"], unique=False)
    op.create_table(
        "memory_candidates",
        sa.Column("scene_version_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_type", sa.String(length=40), nullable=False),
        sa.Column("target_entity_type", sa.String(length=40), nullable=False),
        sa.Column("target_entity_id", sa.String(length=36), nullable=True),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scene_version_id"],
            ["scene_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_candidates_scene_version_id"), "memory_candidates", ["scene_version_id"], unique=False
    )
    op.create_table(
        "review_issues",
        sa.Column("scene_version_id", sa.String(length=36), nullable=False),
        sa.Column("issue_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("conflict_rule", sa.Text(), nullable=False),
        sa.Column("suggestion", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["scene_version_id"],
            ["scene_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_issues_scene_version_id"), "review_issues", ["scene_version_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_issues_scene_version_id"), table_name="review_issues")
    op.drop_table("review_issues")
    op.drop_index(op.f("ix_memory_candidates_scene_version_id"), table_name="memory_candidates")
    op.drop_table("memory_candidates")
    op.drop_index(op.f("ix_workflow_runs_scene_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_timeline_events_project_id"), table_name="timeline_events")
    op.drop_table("timeline_events")
    # ### end Alembic commands ###
