"""add interview sessions and story candidates

Revision ID: e80d1d1f3685
Revises: cd42fd8f8e0e
Create Date: 2026-06-28 20:13:10.713366
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80d1d1f3685'
down_revision: Union[str, None] = 'cd42fd8f8e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('messages_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_project_id'), 'interview_sessions', ['project_id'], unique=False)
    op.create_table('story_candidates',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('proposal', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('applied_entity_type', sa.String(length=40), nullable=True),
    sa.Column('applied_entity_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['novel_projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_candidates_project_id'), 'story_candidates', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_candidates_session_id'), 'story_candidates', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_candidates_session_id'), table_name='story_candidates')
    op.drop_index(op.f('ix_story_candidates_project_id'), table_name='story_candidates')
    op.drop_table('story_candidates')
    op.drop_index(op.f('ix_interview_sessions_project_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
